# Generated by Django 5.2.8 on 2025-11-13 23:08

import django.db.models.deletion
import juego.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=juego.models.generar_codigo, max_length=6, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_ganadas', to=settings.AUTH_USER_MODEL)),
                ('jugador_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_jugador1', to=settings.AUTH_USER_MODEL)),
                ('jugador_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_jugador2', to=settings.AUTH_USER_MODEL)),
                ('sala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='juego.sala')),
                ('turno_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turno_actual', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
